name: Send email on POST request

on:
  repository_dispatch:
    types: [external_post]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: checking code...
      uses: actions/checkout@v2

    - name: Configure Python...
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute script Python
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python send_email_params.py
